<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.5.2</Version>
    <FileVersion>1.5.2.0</FileVersion>
    <AssemblyVersion>1.5.2.0</AssemblyVersion>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MidiFilter</AssemblyName>
    <RootNamespace>MidiFilter</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>b7i6gf</Company>
    <Authors>b7i6gf</Authors>
    <Product>MidiFilter</Product>
    <AssemblyTitle>MidiFilter</AssemblyTitle>
    <Description>A C# tool that forwards MIDI signals from a keyboard while filtering out selected control change messages.</Description>
    <Copyright>Copyright (c) 2026 b7i6gf</Copyright>


    <ApplicationIcon>midi.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <EmbeddedResource Include="midi.ico" />
  </ItemGroup>

</Project>
